### ISSUE TITLE
[Bug]: CUDA out of memory

### ISSUE THREAD

**Issue by misaka10843** [sd-webui/stable-diffusion-webui#1485]
### What happened?

Start the webui After cmd, CUDA out of memory will pop up when there is no IP address. What should I do?

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Relevant log output

```shell
Environment name is set as ldm as per environment.yaml
anaconda3/miniconda3 detected in D:\miniconda3
Stashing local changes and pulling latest update...
No local changes to save
Already up to date.
Do you want to restore changes you made before updating? (Y/N): n
Removing changes please wait...
No stash entries found.
Changes removed, press any key to continue...
Current  environment.yaml hash: 5b05977e89f92b2aa68ba21cbf3569e07239463c
Previous environment.yaml hash: 5b05977e89f92b2aa68ba21cbf3569e07239463c
environment.yaml unchanged. dependencies should be up to date.
if you still have unresolved dependencies, delete "z_version_env.tmp"
Relauncher: Launching...
LDSR not found at path, please make sure you have cloned the LDSR repo to ./models/ldsr/
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "scripts/webui.py", line 532, in <module>
    model, device,config = load_SD_model()
  File "scripts/webui.py", line 523, in load_SD_model
    model = load_model_from_config(config, opt.ckpt)
  File "scripts/webui.py", line 223, in load_model_from_config
    model.cuda()
  File "D:\miniconda3\envs\ldm\lib\site-packages\pytorch_lightning\core\mixins\device_dtype_mixin.py", line 127, in cuda
    return super().cuda(device=device)
  File "D:\miniconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 688, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "D:\miniconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "D:\miniconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "D:\miniconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "D:\miniconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 601, in _apply
    param_applied = fn(param)
  File "D:\miniconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 688, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.37 GiB already allocated; 0 bytes free; 3.42 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by misaka10843** [comment]
I found the reason. The reason is that my VRAM is only 4GB, so I need to change `optimized` to `true` in `relauncher.py`
